<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Learn about natural history.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style4 {
            width: 62px;
            font-size: xx-large;
        }
        .auto-style5 {
            height: 55px;
        }
        .auto-style6 {
            width: 596px;
            font-size: large;
            color: #FFFF00;
            font-family: Arial, Helvetica, sans-serif;
        }
        .auto-style7 {
            width: 62px;
            font-size: medium;
            height: 113px;
        }
        .auto-style9 {
            width: 596px;
            height: 113px;
        }
        .newStyle2 {
            font-family: Arial, Helvetica, sans-serif;
            font-size: medium;
            color: #FFFF00;
            background-color: #007A7A;
        }
        .auto-style10 {
            width: 333px;
            font-size: small;
        }
        .auto-style11 {
            width: 333px;
            height: 113px;
        }
        .auto-style12 {
            margin-left: 0px;
        }
        .auto-style13 {
            font-size: large;
            color: #FFFF00;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
    <link href="StyleSheet.css" rel="stylesheet" type="text/css" />
    <link href="StyleSheet2.css" rel="stylesheet" type="text/css" />
    <link href="StyleSheet2.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="ContentPlaceHolder1">
        
            <p class="auto-style1">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </p>
            <p>
                <table class="auto-style1">
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                <asp:Label ID="Label2" runat="server" BackColor="Teal" Text="Learn about natural history here !" Font-Size="X-Large"></asp:Label>
                        </td>
                        <td class="auto-style6">
                            <asp:Image ID="Image10" runat="server" Height="120px" ImageUrl="~/Images/Missouri Natural Science Musuem logo.jpg" Width="238px" />
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">
                            <asp:TreeView ID="TreeView1" runat="server" BackColor="#009999" BorderColor="Black" Height="126px" Width="255px" Font-Bold="True" Font-Names="Candara" ForeColor="Yellow" ShowLines="True" Font-Size="Large">
                                <Nodes>
                                    <asp:TreeNode NavigateUrl="~/Default.aspx" Text="Home" Value="Home"></asp:TreeNode>
<asp:TreeNode Text="Learn about natural history !" Value="Learn about wildlife !" NavigateUrl="~/Learn about natural history.aspx"></asp:TreeNode>
                                    <asp:TreeNode NavigateUrl="~/VisitUs.aspx" Text="Visit us" Value="Visit Us"></asp:TreeNode>
                                    <asp:TreeNode NavigateUrl="~/Login.aspx" Text="Book here !" Value="Book here !"></asp:TreeNode>
                                    <asp:TreeNode NavigateUrl="~/About us.aspx" Text="About us" Value="Default"></asp:TreeNode>
                                </Nodes>
                            </asp:TreeView>
                        </td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style7">
                            &nbsp;</td>
                        <td class="auto-style11">
                        <p class="auto-style5" style="background-color: #008080; border-bottom-color: rgb(112, 112, 112); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(112, 112, 112); border-left-style: none; border-left-width: 0px; border-right-color: rgb(112, 112, 112); border-right-style: none; border-right-width: 0px; border-top-color: rgb(112, 112, 112); border-top-style: none; border-top-width: 0px; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 14.4px; margin-bottom: 15.6px; margin-left: 0px; margin-right: 10px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                            Extinct mammals of the last Ice Age :<br style="border-bottom-color: rgb(112, 112, 112); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(112, 112, 112); border-left-style: none; border-left-width: 0px; border-right-color: rgb(112, 112, 112); border-right-style: none; border-right-width: 0px; border-top-color: rgb(112, 112, 112); border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;" />
                        </p>
                        </td>
                        <td class="auto-style9">
                            <asp:ImageButton ID="ImageButton1" runat="server" Height="56px" ImageUrl="~/Images/Book-Here.png" PostBackUrl="~/Registered Visitors/Login.aspx" Width="141px" CssClass="auto-style13"/>
                            </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image1" runat="server" Height="362px" ImageUrl="~/Images/giantDeer.jpg" Width="357px" />
                            <br />
                            Depiction of the giant deer.</td>
                        <td class="auto-style6">
                            <p style="font-size: large; color: #FFFF00; background-color: #007A7A">
                                The Giant Deer:</p>
                            <p style="font-size: medium; color: #FFFF00; background-color: #007A7A; line-height: normal; text-align: left; letter-spacing: normal;">
                                The giant deer (<em>Megaloceros giganteus)</em> is sometimes referred to as the Irish elk, although it must be noted that it’s not an elk at all, its closest living relative is in actual fact the Fallow deer. The giant deer ranged right across Eurasia from Ireland in the west through to Siberia and China in the east. Its remains have also been found in North Africa. Similar to the woolly rhino it was probably absent from the southern regions of Europe.</p>
                            <p style="font-size: medium; background-color: #008080">
                                The name ‘giant deer’ comes from its hefty size; it weighed up to 1000Ib’s and stood roughly 7 feet tall at the shoulder. So in terms of height it was roughly equal to a moose, but a little more lightly built. Its alternative name, the Irish elk derives from the abundance of bones recovered from Irish peat bogs. Amazingly, giant deer remains outnumber all other mammalian remains found in Ireland, with over a hundred individuals recovered from the Ballybetagh Bog near Dublin.<br style="border-bottom-color: rgb(112, 112, 112); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(112, 112, 112); border-left-style: none; border-left-width: 0px; border-right-color: rgb(112, 112, 112); border-right-style: none; border-right-width: 0px; border-top-color: rgb(112, 112, 112); border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px;" />
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image2" runat="server" Height="305px" ImageUrl="~/Images/aurochs.jpg" Width="350px" />
                            <br />
                            Aritst&#39;s intepretation of the auroch.</td>
                        <td class="auto-style6" style="font-size: medium; background-color: #008080; color: #FFFF00; font-family: Arial;">
                            <p style="font-size: large; color: #FFFF00; background-color: #007A7A">
                                The Aurochs:
                            </p>
                            <p style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 10.35px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                                The aurochs (<em style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0)">Bos primigenius)</em> or wild ox was the ancestor of all European breeds of domestic cattle, and it survived long after the Ice age ended. Our modern cattle are mere pygmies compared to the aurochs, which stood almost 7 feet tall at the shoulder. The bulls were much bigger than the cows and had longer horns that pointed forward rather than sweeping out to the side, like we see in modern cattle.</p>
                            <p style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 10.35px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                                Intriguingly, cave paintings of the aurochs show that the bulls were mostly black, with some possessing a saddle patch of a lighter colour, while the cows and calves were mostly reddish brown in colour. The aurochs inhabited forests and open scrubland, so they were more numerous during the warmer phases of the Ice age.</p>
                            <p style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 10.35px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                                Ancient Greek and Roman writers help shed light on the behaviour of the aurochs by telling us that it was a very aggressive animal with herd members cooperatively using their great size to defend themselves from predators, much as the African buffalo does today to ward off large predators such as lions.
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image3" runat="server" Height="315px" ImageUrl="~/Images/CaveLion.jpg" Width="353px" />
                            <br />
                            Aritst&#39;s intepretation of the cave lion.<br />
                            <br />
                            <asp:Image ID="Image4" runat="server" Height="299px" ImageUrl="~/Images/Lions_painting,_Chauvet_Cave.jpg" Width="351px" />
                            <br />
                            Prehistoric painting found<br />
                            in Chauvet cave in France depicting the cave lion.<br />
                        </td>
                        <td class="auto-style6" style="font-size: small; color: #FFFF00">
                            <p style="background-color: transparent; box-sizing: border-box; color: rgb(255, 255, 0); direction: ltr; font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 25.6px; margin-bottom: 8px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px; helvetica: ">
                                <b style="box-sizing: border-box; font-weight: 700; line-height: 25.6px; font-size: large;">The Cave lion :</b></p>
                            <p style="background-color: transparent; box-sizing: border-box; color: rgb(255, 255, 0); direction: ltr; font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 25.6px; margin-bottom: 8px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px; helvetica:">
                                <b style="box-sizing: border-box; font-weight: 700; line-height: 25.6px; font-size: medium;">The Cave lion,</b> also known as <b style="box-sizing: border-box; font-weight: 400; line-height: 25.6px;">European cave lion</b> and <b style="box-sizing: border-box; font-weight: 700; line-height: 25.6px;">Eurasian cave lion,</b> is the common name for an extinct, large, wild felid, <i style="box-sizing: border-box; font-style: italic; line-height: 25.6px;"><b style="box-sizing: border-box; font-weight: 700; line-height: 25.6px;">Panthera leo spelaea</b></i> (or <i style="box-sizing: border-box; font-style: italic; line-height: 25.6px;"><b style="box-sizing: border-box; font-weight: 700; line-height: 25.6px;">P. spelaea</b></i>), which lived from about 370,000 to 10,000 years ago. Known from <b style="box-sizing: border-box; color: rgb(255, 255, 0); line-height: 25.6px; text-decoration: none;" title="Fossil">fossils</b> and multiple examples of prehistoric 
                                art, the cave lion is characterized by its large size (larger than the modern lion), rounded, protruding ears, tufted tail, and perhaps faint, <b style="box-sizing: border-box; color: rgb(255, 255, 0); line-height: 25.6px; text-decoration: none;" title="Tiger">tiger</b>-like stripes. While commonly considered an extinct subspecies of the <b style="box-sizing: border-box; color: rgb(255, 255, 0); line-height: 25.6px; text-decoration: none;" title="Lion">lion</a> <i style="box-sizing: border-box; font-style: italic; line-height: 25.6px; color: #FFFF00;">(Panthera leo)</i>, the cave lion is considered by some as a separate species.</p>
                            <p style="background-color: transparent; box-sizing: border-box; color: rgb(255, 255, 0); direction: ltr; font-family: &amp;quot; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 25.6px; margin-bottom: 8px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px; helvetica:">
                                Inhabiting Europe until about the time of the last European Ice Age, the cave lion lived at the same time as <b style="box-sizing: border-box; color: rgb(255, 255, 0); line-height: 25.6px; text-decoration: none;" title="Neanderthal">Neanderthals</b> (250,000 years ago until 30,000 years ago) and the <b style="box-sizing: border-box; color: rgb(255, 255, 0); line-height: 25.6px; text-decoration: none;" title="Cro-Magnon">Cro-Magnon</b> man (40,000 to 10,000 years ago) and have been depicted in cave paintings, among other art. The common name comes from their graphic appearance in caves, although they probably did not live in them.</p>
                            <p style="background-color: transparent; box-sizing: border-box; color: rgb(255, 255, 0); direction: ltr; font-family: &amp;quot; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 25.6px; margin-bottom: 8px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px; helvetica:">
                                During its time, the cave lion was one of the key members of the Pleistocene fauna in Eurasia, during which time it was widespread. For human beings, various archeological artifacts suggest that they were featured in Paleolithic religius rituals. Also, they were hunted by humans.</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">The wooly mammoth:</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image5" runat="server" Height="320px" ImageUrl="~/Images/Woolly_mammoth.jpg" Width="351px" />
                            <br />
                            Computer generated image depicting the wooly mammoth.</td>
                        <td class="auto-style6"><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">The </span><b style="background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">woolly mammoth</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: 13.93px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            (</span><i style="background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: italic; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Mammuthus primigenius</i><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">) is an extinct species of </span>
                            <b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Mammoth">mammoth</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            that lived during the </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Pleistocene">Pleistocene</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            epoch, and was one of the last in a line of mammoth species, beginning with </span><i style="background-color: transparent; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 13.93px; font-style: italic; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
                            <b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size: medium;" title="Mammuthus subplanifrons">Mammuthus subplanifrons</b></i><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            in the early </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Pliocene">Pliocene</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            The woolly mammoth diverged from the </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Steppe mammoth">steppe mammoth</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            about 400,000 years ago in East Asia. Its closest extant relative is the </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Asian elephant">Asian elephant</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            The appearance and behaviour of this species are among the best studied of any </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Prehistory">prehistoric</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            animal because of the discovery of frozen carcasses in </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Siberia">Siberia</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            and </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Alaska">Alaska</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">, 
                            as well as skeletons, teeth, stomach contents, dung, and depiction from life in prehistoric </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Cave painting">cave paintings</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            Mammoth remains had long been known in Asia before they became known to Europeans in the 17th century. The origin of these remains was long a matter of debate, and often explained as being remains of </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Legendary creature">legendary creatures</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            The mammoth was identified as an extinct species of elephant by </span><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px" title="Georges Cuvier">Georges Cuvier</b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            in 1796,</span></td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">The Cave hyena:</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image6" runat="server" Height="389px" ImageUrl="~/Images/caveHyena.jpg" Width="355px" />
                            <br />
                            Reconstruction of the Cave Hyena.</td>
                        <td class="auto-style6">
                            <p style="background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: 22.28px; margin-bottom: 6.96px; margin-left: 0px; margin-right: 0px; margin-top: 6.96px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                                The <b style="line-height: 22.28px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px;">cave hyena</b> (<i style="line-height: 22.28px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px;">Crocuta crocuta spelaea</i>), also known as the <b style="line-height: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px;">Ice Age spotted hyena</b>, was a <b style="font: inherit; background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none; font-family: Arial, Helvetica, sans-serif;" title="Paleosubspecies">paleosubspecies</b> of
                                the
                                <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Spotted hyena">spotted hyena</a> which ranged from the <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Iberian Peninsula">Iberian Peninsula</a> to eastern
                                <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Siberia">Siberia</a>. It is one of the best known mammals of the <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Ice Age">Ice Age</a> and is well represented in many European bone caves.The cave hyena was a highly specialised animal, with its progressive and regressive features being more developed than 
                                in its modern African relative. It preyed on large mammals (primarily <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Wild horse">wild horses</a>, <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Steppe bison">steppe bison</a> and
                                <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Woolly rhinoceros">woolly rhinoceros</a>), and was responsible for the accumulation of hundreds of large Pleistocene mammal bones in areas including horizontal <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Cave">caves</a>,
                                <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Sinkhole">sinkholes</a>, mud pits and muddy areas along rivers.</p>
                            <p style="background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: inherit; margin-bottom: 6.96px; margin-left: 0px; margin-right: 0px; margin-top: 6.96px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                                The cause of the cave hyena&#39;s extinction is not fully understood, though it could have been due to a combination of factors, including <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); text-decoration: none" title="Climate change">climate change</a> and competition with other predators.<sup id="cite_ref-stiner_6-0" class="reference" style="font-size: 9.26px; font-style: normal; font-weight: 400; line-height: 9.26px; white-space: nowrap;"><b style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;"></b></sup></p>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image8" runat="server" Height="303px" ImageUrl="~/Images/Rhinocéros_grotte_Chauvet.jpg" Width="350px" />
                            <br />
                            Prehistoric painting found<br />
                            in Chauvet cave in France, depicting the wooly rhino.</td>
                        <td class="auto-style9">
                            <strong style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; border-bottom-color: rgb(0, 0, 0); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(0, 0, 0); border-left-style: none; border-left-width: 0px; border-right-color: rgb(0, 0, 0); border-right-style: none; border-right-width: 0px; border-top-color: rgb(0, 0, 0); border-top-style: none; border-top-width: 0px; box-sizing: border-box; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: large; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; outline-color: invert; outline-style: none; outline-width: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                            Wooly rhinoceros:<br />
                            <br />
                            </strong><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">The wooly rhino (genus </span>
                            <em style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; border-bottom-color: rgb(0, 0, 0); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(0, 0, 0); border-left-style: none; border-left-width: 0px; border-right-color: rgb(0, 0, 0); border-right-style: none; border-right-width: 0px; border-top-color: rgb(0, 0, 0); border-top-style: none; border-top-width: 0px; box-sizing: border-box; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; outline-color: invert; outline-style: none; outline-width: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                            Coelodonta</em><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">), either of two extinct species of </span>
                            <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">rhinoceros</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            found in </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">fossil</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            deposits of the </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Pliocene</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            and </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Pleistocene epochs</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            (5.3 million to 11,700 years ago) in </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Europe</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: 18px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">,
                            </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">North Africa</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">, 
                            and </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Asia</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            It probably evolved from an earlier form, </span>
                            <em style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; border-bottom-color: rgb(0, 0, 0); border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(0, 0, 0); border-left-style: none; border-left-width: 0px; border-right-color: rgb(0, 0, 0); border-right-style: none; border-right-width: 0px; border-top-color: rgb(0, 0, 0); border-top-style: none; border-top-width: 0px; box-sizing: border-box; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: italic; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; outline-color: invert; outline-style: none; outline-width: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">
                            Dicerorhinus</em><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">, somewhere in northeastern Asia, entered the European region, and became extinct at the end of the most recent </span>
                            <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">ice age</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            The </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">animal</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            was massive, with two large horns toward the front of the </span><a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">skull</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">, 
                            and was covered with a thick coat of hair.The woolly rhinoceros was also present in more temperate, nonglacial regions, where it inhabited 
                            <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">grasslands</a>. 
                            It was a popular subject for <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; box-sizing: border-box; color: rgb(255, 255, 0); cursor: pointer; font-family: Montserrat, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; vertical-align: baseline; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">Stone Age</a> 
                            painters and sculptors; their representations of the woolly rhinoceros, some of which are very accurate, are known from several localities.</span></td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <br />
                            </td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">The Cave Bear</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">
                            <asp:Image ID="Image9" runat="server" Height="348px" ImageUrl="~/Images/Ursus_spelaeus_Sergiodlarosa.jpg" Width="361px" CssClass="auto-style12" />
                            Computer generated image depicting the Cave Bear.</td>
                        <td class="auto-style6"><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">The European Cave Bear or </span><i style="background-color: transparent; color: rgb(255, 255, 0); font-family: 'Times New Roman'; font-size: medium; font-style: italic; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"><b>Ursus spelaeus</b></i><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"> 
                            existed during two different ice ages and is one of the best known mammals of the Ice Age. It is believed to have evolved from the </span><b style="background-color: transparent; color: rgb(255, 255, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"><b>Etruscan Bear</b></b><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px; line-height: normal;"> 
                            (possibly Ursus deningeri) and lived from 5.3 million years ago to about 10,000 years ago. The cave bear&#39;s lifespan is believed to have been 20 years or less. The name spelaeus was taken from the ancient Roman word spelaio meaning cave. It was given the name, </span><i style="background-color: transparent; color: rgb(255, 255, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px"><b>Ursus spelaeus</b></i><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">, 
                            because most of the cave bear&#39;s remains have been found in caves. T<span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, freesans, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">he bears that lived in Europe through the ice ages were bigger than the largest bears alive today, </span>
                            <a style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(255, 255, 0); font-family: Arial, Helvetica, freesans, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: -0.1px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">the grizzlies</a><span style="display: inline !important; float: none; background-color: transparent; color: rgb(255, 255, 0); font-family: Arial, Helvetica, freesans, sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; line-height: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px">. 
                            At 1.5m tall at the shoulder and nearly 3m long, they were formidable giants, weighing in at 880lb (400kg).</span></span></td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">&nbsp;</td>
                        <td class="auto-style10">&nbsp;</td>
                        <td class="auto-style6">&nbsp;</td>
                    </tr>
                </table>
            </p>
            <p>
            </p>
</asp:Content>


